### ISSUE TITLE
[Component] universal grid

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/logos-docusaurus-plugins#116]
We need a universal Grid component that can be used to create grid layouts with various number of columns per breakpoints. so the 

**Features to implement**
- [ ] should handle any specific combination of br<>columns. 
- [ ] Gap
- [ ] NumberOfColumns
- [ ] support for single row (where we have one single row and scrollable horizontally)
- [ ] How many Columns in view

**TODO post implementation**
Once the component is ready we need to replace/adjust existing
- [ ] ProfileCards need to be become single ProfileCard
- [ ] Roadmap 
- [ ] Social Cards 
- [ ] PoweredBy
